# Generated by Django 2.2.5 on 2020-03-02 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='creator',
            new_name='user',
        ),
    ]
