# Generated by Django 2.2.5 on 2020-02-28 22:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 28, 22, 12, 25, 933684, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(default=datetime.datetime(2020, 2, 28, 22, 12, 35, 372754, tzinfo=utc), upload_to='media/post/'),
            preserve_default=False,
        ),
    ]
