# Generated by Django 2.2.5 on 2020-02-28 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200228_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='createdDate',
        ),
    ]
